"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q6)(9p#496c_-@lsvj-bni-l#$^u0cfy$fy^o6%6-3l_ie1rd5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [
#     "vaultify-43wm.onrender.com",       # your backend's Render domain
#     "vaultifybackend.onrender.com",         # optional - your custom domain if any
#     "localhost",                        # optional - for local testing
#     "127.0.0.1",                        # optional - for local testing
# ]
# ALLOWED_HOSTS = ['*']
# CORS_ALLOW_ALL_ORIGINS = False  # disable wildcard
# CORS_ALLOW_CREDENTIALS = True

# # CORS_ALLOWED_ORIGINS = [
# #     "http://localhost:5173",  
# #     "https://vaultifyadmin.africa/"
# # ]
# # CORS_ALLOWED_ORIGINS = ["*"]
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5173",
#     "https://vaultifyadmin.africa/",
# ]
# ---------- CORS & CSRF ----------
# EXACT origins of your frontend(s); no trailing slash
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://vaultifyadmin.africa",
    # add your Render frontend domain if you have one, e.g.:
    # "https://vaultify-frontend.onrender.com",
]

# If your frontend sends cookies (fetch with credentials: "include"),
# set this to True; otherwise leave False for JWT via Authorization header.
CORS_ALLOW_CREDENTIALS = False  # True only when using cookies/sessions

# If you need the Authorization header (JWT), make sure it's allowed:
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + ["authorization"]

# Optional: methods are fine by default, but you can be explicit:
# from corsheaders.defaults import default_methods
# CORS_ALLOW_METHODS = list(default_methods)

# CSRF is only needed if you use cookie-based auth/SessionAuth.
# Keep these for admin pages or if you later switch to cookies:
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://vaultifyadmin.africa",
    # "https://vaultify-backend.onrender.com",  # your backend custom domain if any
]

# ---------- HOSTS ----------
# Render will send requests from its domain; list them here.
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "vaultify-backend.onrender.com",  # replace with your actual backend Render domain
    "vaultifyadmin.africa",           # if you terminate requests on this domain
]


# Or set the CSRF middleware to do nothing (not recommended)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    # 'storages',  
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # sessions first
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # then CSRF middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOWED_ORIGINS = [
#     "https://vaultifyadmin.onrender.com",  # 👈 Your frontend URL
# ]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url
import os

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    # 'default': dj_database_url.config(default='postgresql://vaultifydb_user:bzCxP5iz8QoLX8g6tdyuSTNd3T9kps7b@dpg-d27fncuuk2gs73e4a7i0-a.oregon-postgres.render.com/vaultifydb')

}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'vaultifyadmindb',
#         'USER': 'vaultifyadmindb_user',
#         'PASSWORD': 'sZiDhg7pVWRcSrRJdGPijKqymHZGbLZT',
#         'HOST': 'dpg-d1vbld49c44c73dnsj3g-a.oregon-postgres.render.com',
#         'PORT': '5432',
#         'OPTIONS': {
#             'sslmode': 'require',
#         },
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / "static"]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration with JWT Authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # or your custom permissions
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}
# ---------------------------
# S3 / Linode Object Storage (Legacy E0)
# ---------------------------
# settings.py (additions/changes)

# --- Linode Object Storage (S3-compatible) ---
if os.getenv("USE_S3_MEDIA") == "1":
    INSTALLED_APPS += ["storages"]

    AWS_ACCESS_KEY_ID        = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY    = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME  = os.getenv("AWS_STORAGE_BUCKET_NAME", "vaultify")
    AWS_S3_REGION_NAME       = os.getenv("AWS_S3_REGION_NAME", "us-southeast-1")
    AWS_S3_ENDPOINT_URL      = os.getenv("AWS_S3_ENDPOINT_URL", "https://us-southeast-1.linodeobjects.com")

    # Use VIRTUAL-HOST style with Linode
    AWS_S3_ADDRESSING_STYLE  = "virtual"
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_FILE_OVERWRITE    = False
    AWS_QUERYSTRING_AUTH     = False

    # If your bucket has "Bucket owner enforced" (ACLs disabled), keep this None:
    AWS_DEFAULT_ACL          = None

    # Build custom domain and media URL for virtual-host addressing
    AWS_S3_CUSTOM_DOMAIN     = f"{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace('https://','')}"
    MEDIA_URL                = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

    DEFAULT_FILE_STORAGE     = "storages.backends.s3boto3.S3Boto3Storage"

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }
else:
    STORAGES = {
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }
    MEDIA_URL  = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

