# Generated by Django 5.1.4 on 2025-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254, unique=True)),
                ('adminRole', models.CharField(max_length=50)),
                ('adminPassword', models.CharField(max_length=128)),
            ],
        ),
    ]
