# Generated by Django 5.1.4 on 2025-07-18 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='admin',
         field=models.ForeignKey(
    on_delete=django.db.models.deletion.CASCADE,
    related_name='providers',
    to='api.admin',
    null=True,
),
        ),
    ]
