# Generated by Django 5.1.4 on 2025-07-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_provider_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('public_date', models.DateTimeField()),
                ('estate', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='admin',
            field=models.ForeignKey(
    on_delete=django.db.models.deletion.CASCADE,
    related_name='providers',
    to='api.admin',
    null=True,  # ✅ allow null temporarily
),

        ),
    ]
