# Generated by Django 5.1.4 on 2025-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_create_alertattachment_if_missing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="availability",
            field=models.CharField(default="(mon-fri, 8am -5pm)", max_length=100),
        ),
    ]
