# Generated by Django 5.1.4 on 2025-07-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alert_alter_provider_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api.admin'),
            preserve_default=False,
        ),
    ]
