# Generated by Django 5.1.4 on 2025-08-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_provider_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="announcement_image",
            field=models.ImageField(blank=True, null=True, upload_to="alerts/"),
        ),
    ]
