# Generated by Django 5.1.4 on 2025-08-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alert_announcement_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="announcement_image",
        ),
        migrations.CreateModel(
            name="AlertAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_image",
                    models.FileField(blank=True, null=True, upload_to="alerts/"),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.alert",
                    ),
                ),
            ],
        ),
    ]
